{{- if .Values.enabled -}}
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata: {{ include "k8s-php-app-canary.metadata" . | nindent 2 }}
spec:
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleUp.stabilizationWindowSeconds }}
      selectPolicy: {{ .Values.autoscaling.scaleUp.selectPolicy }}
      policies:
        {{- with .Values.autoscaling.scaleUp.policies -}}
        {{ toYaml . | nindent 6 }}
        {{- end }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleDown.stabilizationWindowSeconds }}
      selectPolicy: {{ .Values.autoscaling.scaleDown.selectPolicy }}
      policies:
        {{- with .Values.autoscaling.scaleDown.policies -}}
        {{ toYaml . | nindent 6 }}
        {{- end }}
{{- if .Values.autoscaling.enabled }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
{{- else }}
  minReplicas: {{ .Values.replicas }}
  maxReplicas: {{ .Values.replicas }}
{{- end }}
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ include "k8s-php-app-canary.app_name" . }}
  {{- if .Values.autoscaling.enabled }}
  metrics:
    {{- if .Values.autoscaling.expr }}
      {{- $type := .type | default "Object" }}
      {{- if eq $type "Object" }}
  - type: {{ $type }}
    object:
      metric:
        name: {{ include "k8s-php-app-canary.promrule_record" . }}
      describedObject:
        apiVersion: v1
        kind: {{ .Values.autoscaling.kind | default "Service" }}
        name: {{ include "k8s-php-app-canary.app_name" . }}
      target:
        type: Value
        value: {{ .Values.autoscaling.value | default "10000" }}
      {{- end }}
    {{- end }}
    {{- if .Values.autoscaling.cpuPercent }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.cpuPercent | int }}
    {{- end }}
  {{- end }}
{{- end -}}
