{{- if and .Values.enabled (gt (.Values.replicas | int) 1) -}}
kind: PodDisruptionBudget
apiVersion: policy/v1beta1
metadata: {{ include "k8s-php-app-canary.metadata" . | nindent 2 }}
spec:
  minAvailable: 1
  selector:
    matchLabels: {{ include "k8s-php-app-canary.labels" . | nindent 6 }}
{{- end -}}
