{{- if and .Values.enabled .Values.autoscaling.enabled .Values.autoscaling.expr .Values.roadrunner.metrics.enabled}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "k8s-php-app-canary.app_name" . }}-roadrunner
  labels:
    prometheus: k8s
    {{- include "k8s-php-app-canary.labels" . | nindent 4 }}
    {{- include "k8s-php-app-canary.extra_labels" . | nindent 4 }}
spec:
  groups:
    - name: {{ include "k8s-php-app-canary.app_name" . }}-roadrunner-rules
      rules:
        - expr: |
            max by (service,namespace) (
              max_over_time (
                rr_http_requests_queue{service="{{ $.Values.global.app_name }}", namespace="{{ $.Values.global.namespace }}" }[1m]
              )
            )
          labels:
            k8s_export: '1'
          record: rr_http_requests_queue_max
        - expr: |
            avg by (service,namespace) (
              avg_over_time (
                rr_http_requests_queue{service="{{ $.Values.global.app_name }}", namespace="{{ $.Values.global.namespace }}" }[1m]
              )
            )
          labels:
            k8s_export: '1'
          record: rr_http_requests_queue_avg
        - expr: |
            sum by (service,namespace) (
              max_over_time (
                rr_http_requests_queue{service="{{ $.Values.global.app_name }}", namespace="{{ $.Values.global.namespace }}" }[1m]
              )
            )
          labels:
            k8s_export: '1'
          record: rr_http_requests_queue_sum
{{- end -}}
