apiVersion: v1
entries:
  k8s-php-app-canary:
  - apiVersion: v2
    created: "2023-02-07T14:13:02.288378272Z"
    description: A Helm chart for K8S to deploy web (canary rollout strategy is possible)
    digest: 8326f0ef380be3e7e122d26ed12d6b3992a1df6806b740bcd1003cbdef9b5e6a
    name: k8s-php-app-canary
    type: application
    urls:
    - k8s-php-app-canary-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    created: "2023-02-07T14:13:02.286933468Z"
    description: A Helm chart for K8S to deploy web (canary rollout strategy is possible)
    digest: 6e66d6b2c26ee34dc11c96068d09c71c0891f3520a2b74f9fedb0095d2cc121d
    name: k8s-php-app-canary
    type: application
    urls:
    - k8s-php-app-canary-0.0.1.tgz
    version: 0.0.1
  k8s-php-app-cronjob:
  - apiVersion: v2
    created: "2023-02-07T14:13:02.289623562Z"
    description: A Helm chart for K8S to deploy the php cronjob
    digest: df24e20dbf9b3fd0964fc31a9a48927de10882cb5b7ea1e65196839bf072a7df
    name: k8s-php-app-cronjob
    type: application
    urls:
    - k8s-php-app-cronjob-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    created: "2023-02-07T14:13:02.289011318Z"
    description: A Helm chart for K8S to deploy the php cronjob
    digest: 04ccd9d930316a691c3729fc074a4668522098bf00b275b4e1344b66893cd54f
    name: k8s-php-app-cronjob
    type: application
    urls:
    - k8s-php-app-cronjob-0.0.1.tgz
    version: 0.0.1
  k8s-php-app-worker:
  - apiVersion: v2
    created: "2023-02-07T14:13:02.291345887Z"
    description: A Helm chart for K8S to deploy the php worker application
    digest: c068603d8340bde8be9d96cd04504c877b04fc369fd6801f319233a52adc4c5c
    name: k8s-php-app-worker
    type: application
    urls:
    - k8s-php-app-worker-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    created: "2023-02-07T14:13:02.290468723Z"
    description: A Helm chart for K8S to deploy the php worker application
    digest: 74470f59f6fb632373122a1225b80aca25f3792d559961631f02f52b9e6137f9
    name: k8s-php-app-worker
    type: application
    urls:
    - k8s-php-app-worker-0.0.1.tgz
    version: 0.0.1
generated: "2023-02-07T14:13:02.284829015Z"
