apiVersion: v1
entries:
  k8s-php-app-canary:
  - apiVersion: v2
    created: "2023-05-11T13:58:31.66715138Z"
    description: A Helm chart for K8S to deploy web (canary rollout strategy is possible)
    digest: 12edda87c5d612b17f2ea3f362007aee4ed99b029b98fc04296458cbf43bbf3c
    name: k8s-php-app-canary
    type: application
    urls:
    - k8s-php-app-canary-0.0.1.tgz
    version: 0.0.1
  k8s-php-app-cronjob:
  - apiVersion: v2
    created: "2023-05-11T13:58:31.669220817Z"
    description: A Helm chart for K8S to deploy the php cronjob
    digest: facba2595fe83d349ea5d2d504aa4b747f3ce36e85efd8a60a756d784eb35ad4
    name: k8s-php-app-cronjob
    type: application
    urls:
    - k8s-php-app-cronjob-0.0.1.tgz
    version: 0.0.1
  k8s-php-app-worker:
  - apiVersion: v2
    created: "2023-05-11T13:58:31.671813563Z"
    description: A Helm chart for K8S to deploy the php worker application
    digest: 35bee50bc030724ed4e45d43f558ad26917e91a6a9c608f1d826134328bed57a
    name: k8s-php-app-worker
    type: application
    urls:
    - k8s-php-app-worker-0.0.1.tgz
    version: 0.0.1
generated: "2023-05-11T13:58:31.66600636Z"
