{{- if .Values.enabled -}}
{{- if or (and .Values.autoscaling.enabled (gt (.Values.autoscaling.minReplicas | int) 1)) (and (not .Values.autoscaling.enabled) (gt (.Values.replicas | int) 1)) -}}
kind: PodDisruptionBudget
apiVersion: policy/v1beta1
metadata: {{ include "k8s-php-app-worker.metadata" . | nindent 2 }}
spec:
  minAvailable: 1
  selector:
    matchLabels: {{ include "k8s-php-app-worker.labels" . | nindent 6 }}
{{- end -}}
{{- end -}}
